require './test/cell_test'
require './test/gameplay_test'
require './test/grid_test'
require './test/ship_placement_test'
require './test/player_test'
require './test/ai_test'
require './test/input_validation_test'